name: dmart
description: A pure Dart implementation of the Dmart client that depends on dio.
version: 2.1.3
repository: https://github.com/edraj/flutterdmart

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
